[package]
name = "rinja_fuzzing"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
fuzz = { path = "fuzz"}

pretty-error-debug = "0.3.0"
thiserror = "1.0.63"

[workspace]
members = [".", "fuzz"]

[profile.release]
debug = 1
