[package]
name = "rinja_parser"
version = "0.3.0"
description = "Parser for Rinja templates"
documentation = "https://docs.rs/rinja"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/rinja-rs/rinja"
repository = "https://github.com/rinja-rs/rinja"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2021"
rust-version = "1.71"

[dependencies]
memchr = "2"
nom = { version = "7", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "from_str"
harness = false
