[package]
name = "rinja_testing"
version = "0.3.0"
authors = ["rinja-rs developers"]
workspace = ".."
edition = "2021"
rust-version = "1.71"
publish = false

[features]
default = ["serde_json"]
serde_json = ["dep:serde_json", "rinja/serde_json"]

[dependencies]
rinja = { path = "../rinja", version = "0.3.0" }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
rinja = { path = "../rinja", version = "0.3.0", features = ["serde_json"] }
criterion = "0.5"
phf = { version = "0.11", features = ["macros" ]}
trybuild = "1.0.76"

[[bench]]
name = "all"
harness = false

[[bench]]
name = "normalize_identifier"
harness = false
