[package]
name = "rinja"
version = "0.13.0"
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/rinja"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://rinja.readthedocs.io/"
repository = "https://github.com/rinja-rs/rinja"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2021"
rust-version = "1.65"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["config", "humansize", "num-traits", "urlencode"]
config = ["rinja_derive/config"]
humansize = ["rinja_derive/humansize", "dep_humansize"]
num-traits = ["rinja_derive/num-traits", "dep_num_traits"]
serde-json = ["rinja_derive/serde-json", "serde", "serde_json"]
urlencode = ["rinja_derive/urlencode", "percent-encoding"]
with-actix-web = ["rinja_derive/with-actix-web"]
with-axum = ["rinja_derive/with-axum"]
with-rocket = ["rinja_derive/with-rocket"]
with-warp = ["rinja_derive/with-warp"]

# deprecated
mime = []
mime_guess = []

[dependencies]
rinja_derive = { version = "0.13", path = "../rinja_derive" }
rinja_escape = { version = "0.11", path = "../rinja_escape" }
dep_humansize = { package = "humansize", version = "2", optional = true }
dep_num_traits = { package = "num-traits", version = "0.2.6", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "to-json"
harness = false
required-features = ["serde-json"]

[package.metadata.docs.rs]
features = ["config", "humansize", "num-traits", "serde-json"]
