[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
fuzz_parser = { path = ".." }

libfuzzer-sys = "0.4.7"
